### ISSUE TITLE
Pequeno bugzinho

### ISSUE THREAD

**Issue by samueldeschamps** [alaniscibele/introducao_sobre_flutter#1]
Calcular total de descontos (ou seja, a soma dos descontos dos itens):

https://github.com/alaniscibele/introducao_sobre_flutter/blob/086613b7f82000266f0d66a597b744a9e1581336/lib/fiscal.dart#L29

O correto seria:

`return listaItens.map((e) => e.desconto).reduce((a, b) => a + b);`

**Comment by alaniscibele** [comment]
Ajustado :)
